[package]
name = "hook_notification"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hook_notification"
path = "src/main.rs"
required-features = []


[dependencies]
minhook = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
windows = { version = "0.58", features = [
    "ApplicationModel",
    "Foundation",
    "Foundation_Collections",
    "UI_Notifications",
    "UI_Notifications_Management",
    "Data_Xml_Dom"
] }
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
    "Win32_System_LibraryLoader",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging"
] }